### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by chriscarrollsmith** [robjhyndman/quarto_website_template#2]
I'd be interested in seeing suggestions in the README as to what you think is the best place to host something like this! Does it work with Github Pages, or does the dynamic comment section not allow that?

**Comment by robjhyndman** [comment]
It will work on any hosting platform. Github Pages is a good choice for many people.

**Comment by chriscarrollsmith** [comment]
> It will work on any hosting platform. Github Pages is a good choice for many people.

Awesome, thanks!
